//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверная строка.
        ///Удалите лишние символы после точки с запятой..
        /// </summary>
        internal static string IndexOutOfRangeExceptionMessage {
            get {
                return ResourceManager.GetString("IndexOutOfRangeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Ранее был введён минус — введите цифру от 1 до 9, для продолжения ввода отрицательной константы..
        /// </summary>
        internal static string IsNotOneToNineExceptionMessage {
            get {
                return ResourceManager.GetString("IsNotOneToNineExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Необходимо завершить ввод индекса — введите закрывающуюся квадратную скобку ]..
        /// </summary>
        internal static string IsNotWhSpAndClSqBrExceptionMessage {
            get {
                return ResourceManager.GetString("IsNotWhSpAndClSqBrExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Введите пробел..
        /// </summary>
        internal static string IsNotWhSpExceptionMessage {
            get {
                return ResourceManager.GetString("IsNotWhSpExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* продолжить вводить символы идентификатора — введите букву, либо цифру, либо подчёркивание;
        ///* завершить ввод индекса — введите закрывающуюся квадратную скобку ]..
        /// </summary>
        internal static string IsNotWhSpIdentAndClSqBrExceptionMessage {
            get {
                return ResourceManager.GetString("IsNotWhSpIdentAndClSqBrExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете ввести:
        ///* идентификатор — введите букву, либо подчёркивание;
        ///* целую константу:
        ///** целая константа начинается с цифры от 1 до 9,
        ///** может быть отрицательной: для этого ввести минус,
        ///** может быть нулём..
        /// </summary>
        internal static string IsNotWhSpIdentAndIntConstExceptionMessage {
            get {
                return ResourceManager.GetString("IsNotWhSpIdentAndIntConstExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* продолжить вводить цифры: продолжить ввод константы;
        ///* завершить ввод индекса — введите закрывающуюся квадратную скобку ]..
        /// </summary>
        internal static string IsNotWhSpNumbAndClSqBrExceptionMessage {
            get {
                return ResourceManager.GetString("IsNotWhSpNumbAndClSqBrExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* ввести пробел, чтобы далее вести операцию div или mod;
        ///* ввести символ операции: либо +, либо -, либо *, либо &quot;/;
        ///* завершить ввод — введите точку с запятой..
        /// </summary>
        internal static string IsNotWhSpOrOpsOrSemicolonExceptionMessage {
            get {
                return ResourceManager.GetString("IsNotWhSpOrOpsOrSemicolonExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Введите двоеточие..
        /// </summary>
        internal static string StateClosedSquareBracket1ExceptionMessage {
            get {
                return ResourceManager.GetString("StateClosedSquareBracket1ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Введите знак равенства..
        /// </summary>
        internal static string StateColonExceptionMessage {
            get {
                return ResourceManager.GetString("StateColonExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Продолжатся ввод дробной части константы.
        ///Введите цифру, либо символ степени — латинские буквы e или E..
        /// </summary>
        internal static string StateDot2ExceptionMessage {
            get {
                return ResourceManager.GetString("StateDot2ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Необходимо продолжить ввод степени дробной части константы.
        ///Введите цифру, либо знак степени — + или -..
        /// </summary>
        internal static string StateEExceptionMessage {
            get {
                return ResourceManager.GetString("StateEExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете начать ввод:
        ///* идентификатора — введите букву, либо подчёркивание;
        ///* целой константы — введите цифру, либо минус;
        ///* константы с плавающей точкой — введите точку.&quot;.
        /// </summary>
        internal static string StateEqualsSignExceptionMessage {
            get {
                return ResourceManager.GetString("StateEqualsSignExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* начать ввод степени числа — введите латинскую букву e или E;
        ///* продолжить вводить целую часть константы — введите цифру;
        ///* можете начать ввод дробной части константы — введите точку;
        ///* ввести символ операции: либо +, либо -, либо *, либо \;
        ///* завершить ввод — введите точку с запятой..
        /// </summary>
        internal static string StateFromOneToNine2ExceptionMessage {
            get {
                return ResourceManager.GetString("StateFromOneToNine2ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* продолжить ввод степени дробной части — введите цифру;
        ///* ввести символ операции: либо +, либо -, либо *, либо /;
        ///* начать ввод операций div или mod — введите пробел;
        ///* завершить ввод — введите точку с запятой..
        /// </summary>
        internal static string StateFromOneToNine4ExceptionMessage {
            get {
                return ResourceManager.GetString("StateFromOneToNine4ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* продолжить вводить символы идентификатора переменной — введите букву, либо цифру, либо подчёркивание;
        ///* обратиться к члену переменной — введите точку;
        ///* начать ввод нескольких переменных — введите запятую.&quot;.
        /// </summary>
        internal static string StateIdentifier1ExceptionMessage {
            get {
                return ResourceManager.GetString("StateIdentifier1ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* продолжить вводить символы идентификатора — введите букву, либо цифру, либо подчёркивание;
        ///* ввести следующий индентификатор — введите запятую..
        /// </summary>
        internal static string StateIdentifier2ExceptionMessage {
            get {
                return ResourceManager.GetString("StateIdentifier2ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* продолжить вводить символы идентификатора — введите букву, либо цифру, либо подчёркивание;
        ///* присвоить переменной/-ым значение — введите двоеточие;
        ///* обратиться к элементу массива — введите квадратную скобку..
        /// </summary>
        internal static string StateIdentifier3ExceptionMessage {
            get {
                return ResourceManager.GetString("StateIdentifier3ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* продолжить вводить идентификатор — введите букву, либо цифру, либо подчёркивание;
        ///* обратиться к элементу по индексу — введите квадратную скобку;
        ///* ввести символ операции: либо +, либо -, либо *, либо \;
        ///* завершить ввод — введите точку с запятой;
        ///* начать ввод символьной константы — введите одинарую кавычку..
        /// </summary>
        internal static string StateIdentifier5ExceptionMessage {
            get {
                return ResourceManager.GetString("StateIdentifier5ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* продолжить вводить дробную часть константы — введите либо цифру, либо символ степень — латинскую букву e или E;
        ///* ввести символ операции: +, либо -, либо *, либо \;
        ///* завершить ввод — введите точку с запятой..
        /// </summary>
        internal static string StateNumbersExceptionMessage {
            get {
                return ResourceManager.GetString("StateNumbersExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы завершили ввод символьной константы, никаких более действий с константой не предусмотрено, завершите ввод оператора — введите точку с запятой..
        /// </summary>
        internal static string StateSingleQuotationMark2ExceptionMessage {
            get {
                return ResourceManager.GetString("StateSingleQuotationMark2ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* продолжить вводить переменные — введите запятую;
        ///* закончить ввод переменных: присвоить им значение; для этого нужно ввести ключевой слово DO — введите заглавную букву D..
        /// </summary>
        internal static string StateSpace2ExceptionMessage {
            get {
                return ResourceManager.GetString("StateSpace2ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* ввести символ операции: либо +, либо -, либо *, либо \;
        ///* начать ввод операций mod и div:
        ///** в первом случае введите строчную букву m,
        ///** в втором случае введите строчную букву d;
        ///** завершить ввод — введите точку с запятой..
        /// </summary>
        internal static string StateSpace6Message {
            get {
                return ResourceManager.GetString("StateSpace6Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ.
        ///Вы можете:
        ///* начать ввод дробной части константы — введите точку;
        ///* ввести символ операции: либо +, либо -, либо *, либо \;
        ///* завершить ввод — введите точку с запятой..
        /// </summary>
        internal static string StateZero2ExceptionMessage {
            get {
                return ResourceManager.GetString("StateZero2ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный первый символ идентификатора.
        ///Введите букву, либо подчёркивание..
        /// </summary>
        internal static string WrongIdentifierFirstSymbolExceptionMessage {
            get {
                return ResourceManager.GetString("WrongIdentifierFirstSymbolExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Неверный символ ключевого слова.
        ///Введите заглавную букву ключевого слова..
        /// </summary>
        internal static string WrongSymbOfResWordExceptionMessage {
            get {
                return ResourceManager.GetString("WrongSymbOfResWordExceptionMessage", resourceCulture);
            }
        }
    }
}
